### ISSUE TITLE
TypeError: Cannot set property device_authorization_endpoint of #<Issuer> 

### ISSUE THREAD

**Issue by waterfoul** [gsoft-inc/azure-devops-npm-auth#11]
I downloaded your npm module globally and tried to run it. It doesn't appear to work right now as I got

(node:25238) UnhandledPromiseRejectionWarning: TypeError: Cannot set property device_authorization_endpoint of #<Issuer> which has only a getter
    at Function.assign (<anonymous>)
    at Function.<anonymous> (/usr/local/lib/node_modules/azure-devops-npm-auth/dist/authentication/mso-issuer.js:20:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/azure-devops-npm-auth/dist/authentication/mso-issuer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:25238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by b93rn** [comment]
@yohanb Can you look at this?

**Comment by yohanb** [comment]
hey @b93rn!  Yeah I can have a look today.

**Comment by yohanb** [comment]
Fixed! Please pull latest version (1.0.7) from npm.

**Comment by b93rn** [comment]
The fix works, thanks!
