### ISSUE TITLE
Dependency issue with @types/mocha

### ISSUE THREAD

**Issue by torbenvanassche** [gsoft-inc/azure-devops-npm-auth#12]
Looking through the dependencies of the package.json I have found that the @types/mocha library is not placed in the devDependencies, which is causing our project to crash (since we use jest as per company policy.)

Solution would be to move @types/mocha to devDependencies instead of the regular depencies of the package.

**Comment by torbenvanassche** [comment]
Is it possible you overlooked redeploying it to NPM? Or is this an automated deployment process? @yohanb

**Comment by yohanb** [comment]
totally forgot.  I should probably automate it! 🤣 
I'll publish it later today.
