### ISSUE TITLE
Custom config path

### ISSUE THREAD

**Issue by rajzik** [gsoft-inc/azure-devops-npm-auth#14]
Would be possible to add custom config path to cli?

**Comment by seanblonien** [comment]
Like a custom path to the project's `.npmrc` file? or do you mean something else?

**Comment by rajzik** [comment]
@seanblonien there is automatic resolution of the .npmrc file. 

It would be great to have possibility to set custom path to .npmrc file.

**Comment by seanblonien** [comment]
@rajzik  This should do it #16

**Comment by rajzik** [comment]
I have added two comments, it would be great just to extend functionality.

**Comment by yohanb** [comment]
great stuff guys.  Moving things forward and merging.
