### ISSUE TITLE
How to host your own Azure Active Directory application?

### ISSUE THREAD

**Issue by octogonz** [gsoft-inc/azure-devops-npm-auth#17]
The documentation says:

> If you want to use your own Azure Active Directory application, it's possible to specify the client_id and tenant_id arguments
> . . .
> When creating your own Azure Active Directory application, under the authentication section, you need the configure it to be a public application

But it doesn't explain the details:
1. Where is the source code for the Azure Active Directory application?
2. How do I build it?
3. How do I deploy it?

This GitHub repo seems to only contain code for the CLI tool.

@hbo-iecheruo @D4N14L

**Comment by yohanb** [comment]
Hi @octogonz , that's because it's out of scope of this tool.
If you want to create your own AAD app, [have a look here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app).
