### ISSUE TITLE
Random timeouts generating tokens

### ISSUE THREAD

**Issue by fernandomarquesgarcia** [gsoft-inc/azure-devops-npm-auth#18]
Hi,
I'm using azure-devops-npm-auth to access my organisation's private NPM feed and I have a weird behaviour which is: from time to time it's possible to generate a token (go to the browser, paste code), and, when it works I can generate several times (deleting the .npmrc) and then suddenly  starts to throw timeouts as shown on the image bellow
<img width="1200" alt="Screenshot 2021-02-18 at 17 54 28" src="https://user-images.githubusercontent.com/22918570/108491194-7f874180-729b-11eb-8e30-7ac6109fbe0a.png">

When I get timeouts, if I comment the code that throws the timeout on the timed-out.js (got module) it works again!:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/22918570/108400220-df85d580-7212-11eb-8fa1-d198f15fb227.png">

Can you help?

**Comment by Jmales** [comment]
I'm also having this problem @yohanb . Any workaround that you know of, better than committing the code?

**Comment by yohanb** [comment]
hey guys, not sure what is going on here since it's happening in a dependency.  First thing that comes to mind is updating the npm modules to see if it's already been fixed.

**Comment by yohanb** [comment]
I published 1.0.9 with updated dependencies.  Can you guys try it out please?  Thanks.

**Comment by mpm-os** [comment]
I suspect that this issue will continue to appear, maybe the better solution is to be able to pass a custom timeout to the dependency, as displayed in here:
[](https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing)

**Comment by yohanb** [comment]
@mpm-os thanks for the hint.  I bumped the timeout to 5s (default is 2.5s).
Published in version 1.0.10

**Comment by mpm-os** [comment]
@yohanb I think you forgot to remove a console log :D

**Comment by yohanb** [comment]
@mpm-os indeed, thanks. 
removed and republished.

**Comment by mpm-os** [comment]
We're still having issues with timeouts, is it possible to add a param or something?
