### ISSUE TITLE
No way to skip auth when running in CI environment

### ISSUE THREAD

**Issue by ntziolis** [gsoft-inc/azure-devops-npm-auth#3]
Using this library together with npm `preinstall` script is a great experience when developing locally. Especially when new developers are added to a project. 

But when running in CI environment this setup means that `npm install` will never complete since it is waiting for the login to be completed by the user.

What we need is a way to skip authentication in CI environments (at leas as part of the `preinstall`. This would allow great developer experience locally while not breaking CI environments.

**Comment by ntziolis** [comment]
I have provided a PR #2 that adds this capability. Le me know if you need anything to get this merged in.

**Comment by yohanb** [comment]
Merged!  I had not needed to use it in a CI context yet.
