### ISSUE TITLE
Issues with preinstall script execution

### ISSUE THREAD

**Issue by ntziolis** [gsoft-inc/azure-devops-npm-auth#4]
We have npm preinstall scripts setup as described, but are running into the following 2 issues:
- when calling `npm install` after token is no longer valid
  - `preinstall` script is executed and token is retrieved
  - however the subsequent install fails
- another case is when the users sets up a repo for the very first time and tries to run `npm install`
 -  preinstall script is not executed
 - install fails

Both problems can be fixed by manually running `npm run preinstall` before executing `npm install`, however:
 - this kind of breaks the super nice flow of handling auth automatically
 - and it executes authentication twice

Note:
- in cases where token is expired but refresh token is not everything works like a charm

Any ideas where the error might be?

**Comment by yohanb** [comment]
For the second case (easiest to reproduce),
When you say the preinstall script isn't executed, can you validate that the plugin is called by replacing the preinstall with something like `"echo 'preinstall'"`?
Thanks

**Comment by ntziolis** [comment]
Will try and report back here.

**Comment by yohanb** [comment]
closed for inactivity.

**Comment by ntziolis** [comment]
Sry for the delay:
- The script is executed, thats not the issue
- but it seems like npm is not retrieving the updated credentials when executing the subsequent install

Thinking about it would makes sense that npm reads credentials when npm command is invoked. Any script executed as part of this initial command then operates with those cached credentials.

Again this is only a hunch, but the behaviour would match what we are seeing.
