### ISSUE TITLE
Has the latest code been published?

### ISSUE THREAD

**Issue by christianacca** [gsoft-inc/azure-devops-npm-auth#7]
I'm getting the same error that [PR2](https://github.com/gsoft-inc/azure-devops-npm-auth/pull/2) is meant to fix:

``` cmd
C:\Git\my-project\.npmrc
(node:4816) UnhandledPromiseRejectionWarning: Error: No private registry defined in project .npmrc or user defined .npmrc.
    at getRegistry (C:\Git\my-project\node_modules\azure-devops-npm-auth\dist\index.js:73:15)
```

I'm using azure-devops-npm-auth@1.0.3

That suggests that this fix hasn't yet been published as a new version of this package

**Comment by dennispg** [comment]
I pulled the source and tested with that, and it works really well. It is definitely different than what is deployed to npm. It would be great if it can be updated in npm too!

**Comment by yohanb** [comment]
hey guys, sorry for the late reply. 
I could definitely update the npm package with the latest.  I'll get on it this week! ✌️

**Comment by yohanb** [comment]
Published

**Comment by christianacca** [comment]
Thanks @yohanb :-)
