### ISSUE TITLE
Getting 401 error

### ISSUE THREAD

**Issue by vany0114** [gsoft-inc/azure-devops-npm-auth#9]
Hi @yohanb @ntziolis 

I'm getting this error after to authenticate successfully. Also, I see that the ` .npmrc` file has the tokens there.

`Done! You can now install packages from https://pkgs.dev.azure.com/xxx/xxx/_packaging/xxx/npm/registry/ `

```
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login
```

Do you know what the problem can be?

Thanks in advance!

**Comment by vany0114** [comment]
nvm

**Comment by yohanb** [comment]
@vany0114 can you confirm your permissions on the artifacts feed?
![image](https://user-images.githubusercontent.com/812993/85738273-e5e89f80-b6cd-11ea-86c3-f0b19360dbf6.png)

**Comment by vany0114** [comment]
@yohanb 

![image](https://user-images.githubusercontent.com/12032625/85739569-863ac600-b6c6-11ea-938a-919b800df0b3.png)

**Comment by vany0114** [comment]
maybe it could be the fact that my feed is a project scoped rather than organization scoped?

**Comment by yohanb** [comment]
Could you try with an org scoped feed?

**Comment by yohanb** [comment]
closed for inactivity
